# Generated by Django 5.1.1 on 2025-10-24 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('event_organizer', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=0)),
                ('review_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='event.event')),
                ('event_organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='event_organizer.eventorganizer')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.runner')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('runner', 'event')},
            },
        ),
    ]
