# Generated by Django 5.2.7 on 2025-10-22 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='event_organizer.eventorganizer')),
            ],
        ),
    ]
