# Generated by Django 5.2.7 on 2025-10-23 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_organizer', '0002_remove_eventorganizer_created_at_and_more'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='event_organizer.eventorganizer'),
        ),
    ]
