# Generated by Django 5.2.7 on 2025-10-24 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_organizer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
