# Generated by Django 5.2.7 on 2025-10-22 11:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fun_run', 'Fun Run'), ('5k', '5K'), ('10k', '10K'), ('half_marathon', 'Half Marathon'), ('full_marathon', 'Full Marathon')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('jakarta_barat', 'Jakarta Barat'), ('jakarta_pusat', 'Jakarta Pusat'), ('jakarta_selatan', 'Jakarta Selatan'), ('jakarta_timur', 'Jakarta Timur'), ('jakarta_utara', 'Jakarta Utara'), ('bekasi', 'Bekasi'), ('bogor', 'Bogor'), ('depok', 'Depok'), ('tangerang', 'Tangerang')], max_length=20)),
                ('image', models.URLField(blank=True, null=True)),
                ('image2', models.URLField(blank=True, null=True)),
                ('image3', models.URLField(blank=True, null=True)),
                ('event_date', models.DateTimeField()),
                ('regist_deadline', models.DateTimeField()),
                ('distance', models.PositiveIntegerField(default=0)),
                ('contact', models.CharField(max_length=20)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('total_participans', models.PositiveIntegerField(default=0)),
                ('full', models.BooleanField(default=False)),
                ('user_eo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_organizer.eventorganizer')),
                ('event_category', models.ManyToManyField(related_name='events', to='event.eventcategory')),
            ],
        ),
    ]
