# Generated by Django 5.2.7 on 2025-10-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('coming_soon', 'Coming Soon'), ('on_going', 'On Going'), ('finished', 'Finished')], default='coming_soon', max_length=20),
        ),
    ]
