# Generated by Django 5.1.1 on 2025-10-24 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('event_organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user_eo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_organizer.eventorganizer'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_category',
            field=models.ManyToManyField(related_name='events', to='event.eventcategory'),
        ),
    ]
