# Generated by Django 5.2.7 on 2025-10-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coin',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
