# Generated by Django 5.2.7 on 2025-10-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='distance',
        ),
    ]
