# Generated by Django 5.2.7 on 2025-10-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
        ('event', '0003_auto_20251026_0132'),
    ]

    operations = [
    ]
