# Generated by Django 5.2.7 on 2025-10-23 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_coin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='event',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_category',
        ),
        migrations.CreateModel(
            name='EventCategoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField(default=0)),
                ('coin', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventcategory')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_detail', to='event.event')),
            ],
        ),
    ]
