# Generated by Django 5.2.7 on 2025-10-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_event_coin_remove_event_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coin',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='event_category',
            field=models.ManyToManyField(related_name='events', to='event.eventcategory'),
        ),
        migrations.DeleteModel(
            name='EventCategoryDetail',
        ),
    ]
