# Generated by Django 5.2.7 on 2025-10-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='base_location',
            field=models.CharField(choices=[('jakarta_pusat', 'Jakarta Pusat'), ('jakarta_barat', 'Jakarta Barat'), ('jakarta_selatan', 'Jakarta Selatan'), ('jakarta_timur', 'Jakarta Timur'), ('jakarta_utara', 'Jakarta Utara'), ('bogor', 'Bogor'), ('depok', 'Depok'), ('tangerang', 'Tangerang'), ('tangerang_selatan', 'Tangerang Selatan'), ('bekasi', 'Bekasi')], default='depok', max_length=50),
        ),
    ]
