# Generated by Django 5.2.7 on 2025-10-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='attended_events',
            field=models.ManyToManyField(blank=True, related_name='attendees', to='event.event'),
        ),
    ]
