# Generated by Django 5.2.7 on 2025-10-26 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_runner_email_alter_user_email'),
    ]

    operations = [
    ]
