# Generated by Django 5.2.7 on 2025-10-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_runner_base_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='base_location',
            field=models.CharField(choices=[('jakarta_barat', 'Jakarta Barat'), ('jakarta_pusat', 'Jakarta Pusat'), ('jakarta_selatan', 'Jakarta Selatan'), ('jakarta_timur', 'Jakarta Timur'), ('jakarta_utara', 'Jakarta Utara'), ('bekasi', 'Bekasi'), ('bogor', 'Bogor'), ('depok', 'Depok'), ('tangerang', 'Tangerang')], default='depok', max_length=50),
        ),
    ]
