# Generated by Django 5.2.7 on 2025-10-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_runner_remove_user_base_location_remove_user_poin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runner',
            name='email',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
