# Generated by Django 5.2.7 on 2025-10-25 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
        ('main', '0002_remove_runner_email_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.eventcategory'),
        ),
    ]
