# Generated by Django 5.2.7 on 2025-10-25 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOrganizer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='event_organizer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('base_location', models.CharField(choices=[('jakarta', 'Jakarta'), ('surabaya', 'Surabaya'), ('bandung', 'Bandung'), ('medan', 'Medan'), ('semarang', 'Semarang'), ('makassar', 'Makassar'), ('palembang', 'Palembang'), ('denpasar', 'Denpasar'), ('yogyakarta', 'Yogyakarta'), ('surakarta', 'Surakarta'), ('malang', 'Malang'), ('pekanbaru', 'Pekanbaru'), ('depok', 'Depok')], max_length=50)),
                ('total_events', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('coin', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]