# Generated by Django 5.1.1 on 2025-10-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorganizer',
            name='coin',
            field=models.IntegerField(default=0),
        ),
    ]
