# Generated by Django 5.2.7 on 2025-10-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganizer',
            name='base_location',
            field=models.CharField(choices=[('jakarta_barat', 'Jakarta Barat'), ('jakarta_pusat', 'Jakarta Pusat'), ('jakarta_selatan', 'Jakarta Selatan'), ('jakarta_timur', 'Jakarta Timur'), ('jakarta_utara', 'Jakarta Utara'), ('bekasi', 'Bekasi'), ('bogor', 'Bogor'), ('depok', 'Depok'), ('tangerang', 'Tangerang')], max_length=50),
        ),
    ]
