# Generated by Django 5.2.7 on 2025-10-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_organizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventorganizer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='eventorganizer',
            name='updated_at',
        ),
    ]
