# Generated by Django 5.2.7 on 2025-10-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganizer',
            name='base_location',
            field=models.CharField(choices=[('jakarta', 'Jakarta'), ('surabaya', 'Surabaya'), ('bandung', 'Bandung'), ('medan', 'Medan'), ('semarang', 'Semarang'), ('makassar', 'Makassar'), ('palembang', 'Palembang'), ('denpasar', 'Denpasar'), ('yogyakarta', 'Yogyakarta'), ('surakarta', 'Surakarta'), ('malang', 'Malang'), ('pekanbaru', 'Pekanbaru'), ('depok', 'Depok')], max_length=50),
        ),
    ]
