# Generated by Django 5.2.7 on 2025-10-24 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_organizer', '0002_remove_eventorganizer_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganizer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='event_organizer_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
