# Generated by Django 5.2.6 on 2025-10-26 14:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_organizer', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price_coins', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('category', models.CharField(choices=[('apparel', 'Apparel'), ('accessories', 'Accessories'), ('totebag', 'Tote Bag'), ('water_bottle', 'Water Bottle'), ('other', 'Other')], default='apparel', max_length=30)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchandise', to='event_organizer.eventorganizer')),
            ],
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_item', models.PositiveIntegerField(default=0)),
                ('total_coins', models.PositiveIntegerField(default=0)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('merchandise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='merchandise.merchandise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='main.runner')),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
    ]
