# Generated by Django 5.2.7 on 2025-10-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemption',
            name='price_per_item',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
