# Generated by Django 5.2.7 on 2025-10-23 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_redemption_price_per_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redemption',
            options={'ordering': ['-redeemed_at']},
        ),
        migrations.AddField(
            model_name='redemption',
            name='total_coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='merchandise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='merchandise.merchandise'),
        ),
    ]
